package main.shoppilientmobile.domain.domainExposure

import main.shoppilientmobile.domain.observableEntities.observablePattern.RegisterToObservableSharedShoppingListUseCase

interface ObservableSharedShoppingList: RegisterToObservableSharedShoppingListUseCase {

}